### ISSUE TITLE
Generating PKGBUILD for tensorboad_logger

### ISSUE THREAD

**Issue by fengwang** [anntzer/pypi2pkgbuild#10]
When I was trying to generate for package 'tensorboard_logger' with command 

>  python3 ./pypi2pkgbuild.py git+https://github.com/TeamHG-Memex/tensorboard_logger

I encountered a problem with outputs like this:

```
Traceback (most recent call last):
  File "./pypi2pkgbuild.py", line 1421, in <module>
    sys.exit(main())
  File "./pypi2pkgbuild.py", line 1279, in main
    version="%(prog)s {}".format(__version__))
NameError: name '__version__' is not defined
```

Arch Linux packages 'namcap', 'pkgfile' and python-pip have been installed already.

**Comment by anntzer** [comment]
Pushed a fix on master.  Thanks for the report, feel free to ping for reopen if it still doesn't work.
