### ISSUE TITLE
ModuleNotFoundError: No module named 'pip.vcs'

### ISSUE THREAD

**Issue by hl037** [anntzer/pypi2pkgbuild#11]
```
 $>pypi2pkgbuild.py pypi2pkgbuild
Traceback (most recent call last):
  File "/home/leo/.local/bin/pypi2pkgbuild.py", line 31, in <module>
    from pip.vcs import VersionControl
ModuleNotFoundError: No module named 'pip.vcs'
```

I have this error when trying to do the meta installation from the pypi version...

**Comment by anntzer** [comment]
Fixed in master.  I should really do a new release...
Can you confirm that master works for you?

**Comment by hl037** [comment]
Yes, master works, it's only the pypi version (installed from pip)

**Comment by anntzer** [comment]
0.2 is on pypi now.  Feel free to report additional issues with it.
