### ISSUE TITLE
Passing PKGDEST to makepkg causes namcap to fail

### ISSUE THREAD

**Issue by lhupitr** [anntzer/pypi2pkgbuild#14]
I wanted to have pypi2pkgbuild output the package into a local repo I use with aurutils so I tried passing PKGDEST=/path/to/repo to makepkg and the package built and outputted into the correct destination folder but at the end namcap failed with:
`Subprocess.CalledProcessError: Command '['namcap', 'python-snapcast-2.0.10-00-any.pkg.tar.xz']' returned non-zero exit status 2`

Could PKGDEST be passed on to namcap as well?

**Comment by anntzer** [comment]
Thanks for the report, this should be fixed now (by using package fullpaths); can you please confirm?

**Comment by lhupitr** [comment]
Yes, working fine now. 
Thankyou.
