### ISSUE TITLE
Add LANGUAGE=en.US before exec shell

### ISSUE THREAD

**Issue by felinae98** [anntzer/pypi2pkgbuild#22]
In Chinese environment, `pacman -Qo /usr/lib/python3.10/site-packages/pip-20.3.4-py3.10.egg-info/` will return `/usr/lib/python3.10/site-packages/pip-20.3.4-py3.10.egg-info/ 由 python-pip 20.3.4-4 所拥有`, then the package name and version extract will fail. So please ensure `LANGUAGE=en_US` before execute a shell command.

**Comment by anntzer** [comment]
Does LANG=C work as well? (I would prefer that.)

**Comment by felinae98** [comment]
Yes, LANG=C works fine.

**Comment by anntzer** [comment]
Thanks for the report; this should be fixed now.
