### ISSUE TITLE
Option to skip package building

### ISSUE THREAD

**Issue by Real-Gecko** [anntzer/pypi2pkgbuild#29]
Would be nice to skip build step and simply update `PKGBUILD`.

**Comment by anntzer** [comment]
Does `--makepkg=--nobuild --no-install` do what you want?

**Comment by Real-Gecko** [comment]
Well I guess not completely: https://pastebin.com/waLgGTHT
Note `.whl` file and `src` dir appearing after command is run and also attempt to find `.tar.zst` file.

**Comment by anntzer** [comment]
My Arch machine is temporarily unavailable, so you'll have to fix that by yourself for now, sorry.  (I think a PR that special-cases `--makepkg=--nobuild` to support that use case could be nice.)

**Comment by Real-Gecko** [comment]
Will see what I can do

**Comment by anntzer** [comment]
--nobuild should now work as of master.

**Comment by Real-Gecko** [comment]
Thank you.
