### ISSUE TITLE
Building from local whl file giving "ERROR:pypi2pkgbuild:Package Not found"

### ISSUE THREAD

**Issue by hermstadalex** [anntzer/pypi2pkgbuild#3]
Hello @anntzer, sorry to bother you again!

I recently returned to your library, and I'm finding that the building from a local whl file option is no longer working for me. Here is my usage:

``` 
readlink -f kolibri_static-0.1.1rc1-py2.py3-none-any.whl

>   /home/kol/test/pypi2pkgbuild/kolibri_static-0.1.1rc1-py2.py3-none-any.whl 


pypi2pkgbuild.py -d file:///home/kol/test/pypi2pkgbuild/kolibri_static-0.1.1rc1-py2.py3-none-any.whl
```

And here is the error I am receiving:

``` 
ERROR:pypi2pkgbuild:Package file:///home/kol/test/pypi2pkgbuild/kolibri_static-0.1.1rc1-py2.py3-none-any.whl  not found.
```

Any errors you can see in my usage here? The `readlink -f` command at the beginning was to obtain the absolute path of the file, which I passed into the package call.

**Comment by anntzer** [comment]
Can you try bisecting this (if you know how to do it)?  I have been rewriting the history somewhat freely so it may take a few times before you find a working version though.

**Comment by anntzer** [comment]
Also, does `pip install file:///home/...` work for you?  (Basically pypi2pkgbuild *should* be able to take "paths" in the same format as pip.)

**Comment by hermstadalex** [comment]
`pip install file:///home/kol/test/pypi2pkgbuild/kolibri_static-0.1.1rc1-py2.py3-none-any.whl` does work for me. 

I actually reverted back to the commit with the tag: "Preliminary support for local wheels/sdists." and it still seems to be giving the same error. I'm not sure if it's an issue with this particular whl file or something.

**Comment by anntzer** [comment]
Can you paste the log of `pypi2pkgbuild.py -v file:///` (--verbose)?

**Comment by hermstadalex** [comment]
My mistake posting this issue. It turns out I'd forgotten my usage of the library from before.

Using `pypi2pkgbuild.py -v file:///` does not work for me, however doing `python ./pypi2pkgbuild.py -v file:///` worked perfectly. 

I have one other completely unrelated question/confusion about the library - would you like me to make a new issue or ask it here?

**Comment by anntzer** [comment]
That's strange, did you not install the latest version?  (pypi2pkgbuild can actually package itself as an arch package so you may want to do that using the latest version)

Let's open a new issue, they cost nothing :-)
