### ISSUE TITLE
Getting stuck in endless loop when making PKGBUILD

### ISSUE THREAD

**Issue by jopejoe1** [anntzer/pypi2pkgbuild#33]
When trying to create a PKGBUILD for `git+https://github.com/notofonts/notobuilder` I'm getting stuck in an endless loop.

[output.log](https://github.com/anntzer/pypi2pkgbuild/files/10216548/output.log)*

*Edit: after letting it run over the night, it crashed due to the maximum recursion depth being exceeded updated the log with the full output from that.

**Comment by anntzer** [comment]
Thanks for reporting.  Can you give a try to master?

**Comment by jopejoe1** [comment]
Just tried the latest master and it works now. Thanks
